Repository Schlaue-Lise-IT-Project/schlaue-lise, pull requests merged in 2021-11, with the labels that each got.

#7 Lenas URL Impl übernommen
  actions/actions.py
  data/rules/rules_main.yml
  data/stories/stories_main.yml
Labels: enhancement

#6 Update responses_schlafen.yml - created Endpoints
  data/nlu/responses/responses_schlafen.yml
Labels: enhancement

#5 Hygiene hübsch gemacht + Endpoints
  actions/actions.py
  data/stories/stories_hygiene.yml
  domain.yml
Labels: enhancement

#3 Update user-manual-schlafen-die-zweite.md
  user-manual.md
Labels: documentation

#23 README um Timeout Variable ergänzt
  README.md
Labels: documentation

#24 Bugfix: utter_hallo eingebaut
  data/nlu/responses/responses_main.yml
Labels: bug

#17 Lena/spenden
  .gitignore
  actions/actions.py
  data/nlu/nlu_schlafen.yml
  data/nlu/nlu_spenden.yml
  data/nlu/responses/responses_spenden.yml
  data/rules/rules_spenden.yml
  data/stories/stories_hygiene.yml
  data/stories/stories_spenden.yml
  domain.yml
  story_graph.dot
  user-manual.md
Labels: enhancement

#26 Marie/bot challenge
  data/nlu/nlu_botChallenge.yml
  data/nlu/responses/responses_botChallenge.yml
  data/nlu/responses/responses_main.yml
  data/rules/rules_botChallenge.yml
  data/rules/rules_hygiene.yml
  data/rules/rules_main.yml
  data/stories/stories_botChallenge.yml
  domain.yml
Labels: enhancement

#31 Marie/default fallback
  config.yml
  data/nlu/nlu_default.yml
  data/nlu/nlu_main.yml
  data/nlu/responses/responses_default.yml
  data/nlu/responses/responses_main.yml
  data/rules/rules_default.yml
  data/stories/stories_main.yml
  domain.yml
Labels: enhancement

#16 Bugfix: Divers wird erkannt
  data/nlu/nlu_main.yml
  domain.yml
Labels: bug

#43 Bugfix: Spendenartikel werden nicht erkannt #20
  data/rules/rules_spenden.yml
  data/stories/stories_spenden.yml
  domain.yml
  story_graph.dot
Labels: bug

#42 Tanja/medicine
  actions/actions.py
  data/nlu/nlu_main.yml
  data/nlu/nlu_medicine.yml
  data/nlu/nlu_medicine2.yml
  data/nlu/responses/responses_medicine.yml
  data/rules/rules_medicine.yml
  data/rules/rules_medicine2.yml
  data/stories/stories_medicine.yml
  data/stories/stories_medicine2.yml
  domain.yml
  user-manual.md
Labels: enhancement

#48 in rules und stories schlafen und hygiene action_answer_url eingefügt…
  data/nlu/nlu_hygiene.yml
  data/rules/rules_hygiene.yml
  data/rules/rules_schlafen.yml
  data/stories/stories_hygiene.yml
  data/stories/stories_schlafen.yml
Labels: enhancement

#58 Hygiene Kombi Spende weiterbearbeitet
  data/nlu/responses/responses_spenden.yml
  data/rules/rules_spenden.yml
Labels: enhancement

#50 Update README.md
  README.md
Labels: documentation

#57 Update user-manual.md
  user-manual.md
Labels: documentation

#54 Merge rasax into main
  .github/workflows/action_server.yml
  .github/workflows/rasax-ci.yml
  Dockerfile
  _config.yml
  actions/actions.py
  data/nlu/nlu_hygiene.yml
  data/nlu/nlu_medicine.yml
  data/nlu/nlu_schlafen.yml
  data/nlu/responses/responses_schlafen.yml
  data/rules/rules_schlafen.yml
  data/stories/stories_schlafen.yml
  domain.yml
Labels: enhancement

#49 danke in rules angelegt und responses_main sowie nlu_main erweitert
  data/nlu/nlu_main.yml
  data/nlu/responses/responses_main.yml
  data/rules/rules_main.yml
Labels: enhancement

#65 Tanja/medicine
  data/nlu/nlu_medicine.yml
  data/nlu/responses/responses_medicine.yml
  data/rules/rules_medicine.yml
  data/stories/stories_medicine.yml
Labels: bug, invalid

#71 #66 umgesetzt
  data/nlu/responses/responses_main.yml
  data/nlu/responses/responses_schlafen.yml
  data/stories/stories_main.yml
Labels: enhancement
